package application;

public enum ENUM_Scale_Type {

	/*
	 *  Scale is used to differentiate damage and effects between objects of significantly different sizes.
	 *  The Active Player is always the base for the multiplier. 10^[AP_Scale - PP_Scale]
	 *  Example: a scale 3 (small creature - rat) attacks a scale 4 (medium critter - dog) 
	 */
	
	
	MICRO,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: VS_SCALE_4: VS_SCALE_3: VS_SCALE_2: VS_SCALE_1: 1
	MILLI,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: VS_SCALE_4: VS_SCALE_3: VS_SCALE_2: 1 VS_SCALE_1: 2
	TINY,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: VS_SCALE_4: VS_SCALE_3: 1 VS_SCALE_2: 2 VS_SCALE_1: 3
	SMALL,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: VS_SCALE_4: 1 VS_SCALE_3: 2 VS_SCALE_2: 3 VS_SCALE_1: 4
	MEDIUM,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: 1 VS_SCALE_4: 2 VS_SCALE_3: 3 VS_SCALE_2: 4 VS_SCALE_1: 5
	LARGE,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: 1 VS_SCALE_5: 2 VS_SCALE_4: 3 VS_SCALE_3: 4 VS_SCALE_2: 5 VS_SCALE_1: 6
	HUGE,		// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: VS_SCALE_7: 1 VS_SCALE_6: 2 VS_SCALE_5: 3 VS_SCALE_4: 4 VS_SCALE_3: 5 VS_SCALE_2: 6 VS_SCALE_1: 7
	MONSTROUS,	// VS_SCALE_10: VS_SCALE_9: VS_SCALE_8: 1 VS_SCALE_7: 2 VS_SCALE_6: 3 VS_SCALE_5: 4 VS_SCALE_4: 5 VS_SCALE_3: 6 VS_SCALE_2: 7 VS_SCALE_1: 8 
	TITANIC,	// VS_SCALE_10: 0.1 VS_SCALE_9: 1 VS_SCALE_8: VS_SCALE_7: VS_SCALE_6: VS_SCALE_5: VS_SCALE_4: VS_SCALE_3: VS_SCALE_2: 8 VS_SCALE_1: 9
	EPIC,		// VS_SCALE_10: 1 VS_SCALE_9: 2 VS_SCALE_8: 3 VS_SCALE_7: 4 VS_SCALE_6: 5 VS_SCALE_5: 6 VS_SCALE_4: 7 VS_SCALE_3: 8 VS_SCALE_2: 9 VS_SCALE_1: 10 
	
}
